### ISSUE TITLE
Please confirm SST39SF010 and Linux compatibility

### ISSUE THREAD

**Issue by evgkarasev** [Elrindel/Arduino-Flash-Programmer#1]
Hi!

Thank you for making your excellent piece of work public!

I have reviewed a lot of Arduino EEPROM programmers available within github and found that yours is capable to address large ROMs and use optimal hardware.
Please could confirm the compatibility with SST39SF010 and Linux environment as well.

**Comment by Elrindel** [comment]
Hello,

Thank you for the comment.

The SST39SF010 flash memory is fully compatible (using the default sequence 1)!

I tested with a SST39SF040 and everything is OK.

The Python program is Linux compatible. You have to specify the right serial port with the -p argument.

**Comment by evgkarasev** [comment]
Hi!

Thank you for your prompt reply!

Just read the newspaper article about retrocomputing:

https://www.nytimes.com/2021/01/08/style/retrocomputing.html

And remember our conversation, so it seems that flash ROM based floppy
emulators for old PCs could be a good business!

**Comment by evgkarasev** [comment]
Hi, Elrindel!

Just completed the assembly on breadboard and flashed the Arduino with the code from Arduino/Uno-Nano/ folder.
Flashing was completed without errors.

I use Arduino Nano V3 and AT29C010A flash, assembled the schema without any modifications. 

I run the code under Ubuntu 20.04.
To run the code I installed the following modules:

$ pip3 install serial               
Collecting serial
  Downloading serial-0.0.97-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 1.5 MB/s 
Requirement already satisfied: pyyaml>=3.13 in /usr/lib/python3/dist-packages (from serial) (5.3.1)
Collecting iso8601>=0.1.12
  Downloading iso8601-0.1.13-py2.py3-none-any.whl (9.3 kB)
Requirement already satisfied: future>=0.17.1 in /usr/lib/python3/dist-packages (from serial) (0.18.2)
Installing collected packages: iso8601, serial
Successfully installed iso8601-0.1.13 serial-0.0.97

$ pip3 install comports    
Collecting comports
  Downloading comports-0.1.0-py3-none-any.whl (4.8 kB)
Collecting pyserial
  Downloading pyserial-3.5-py2.py3-none-any.whl (90 kB)
     |████████████████████████████████| 90 kB 1.4 MB/s 
Installing collected packages: pyserial, comports
Successfully installed comports-0.1.0 pyserial-3.5

Then I can run the program without any errors.

$ sudo chmod a+rw /dev/ttyUSB0
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c I -x
FF FF
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c E
Do you really want to erase the memory? [Y/n]y
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c W -a 0 TEST WRITE DATA 
[+] Ready to write 15 bytes
[+] Write 15/15 (15 bytes)
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c R -a 0 -l 32 -x       
E0 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF% 

So it seems it doesn't work as expected...

**Comment by Elrindel** [comment]
Hello,

I don't know why it doesn't work with your AT29C010A.
This memory does use sequence 1 like the SST39SF010.

I don't have an AT29C010A or any other Atmel flash memory, so I can't test.

Have you tested with a SST39SF010?

**Comment by evgkarasev** [comment]
According to vendor datasheets AT29C010 and SST39SF010 are interchangeable, so don't think it could be an issue. 
Now I trace the data on D0-D7 with logical analyzer, and it seems the issue is the timing...

**Comment by Elrindel** [comment]
You can try the version for other Arduino boards: https://github.com/Elrindel/Arduino-Flash-Programmer/blob/master/Arduino/Other/ArduinoFlashProgrammer/ArduinoFlashProgrammer.ino
(This code is slower than the Uno/Nano version)

**Comment by evgkarasev** [comment]
$ sigrok-cli --driver fx2lafw --config samplerate=500000 --channels D0,D1,D2,D3,D4,D5,D6,D7 --continuous -P parallel
parallel-1: d5
parallel-1: ca
parallel-1: df
parallel-1: ab
parallel-1: d5
parallel-1: d7
parallel-1: c2
parallel-1: d5
parallel-1: df
parallel-1: df
parallel-1: ca
parallel-1: df
parallel-1: aa
parallel-1: d5
parallel-1: df
parallel-1: 9f
parallel-1: ff
parallel-1: df
parallel-1: cb
parallel-1: dd
parallel-1: ca
parallel-1: d7
parallel-1: ff
parallel-1: d5
parallel-1: ca
parallel-1: df
parallel-1: c4
parallel-1: d5
parallel-1: df
parallel-1: ab
parallel-1: ff
parallel-1: ca
parallel-1: d7
parallel-1: c2
parallel-1: d5
parallel-1: ca
parallel-1: d3
parallel-1: ff
parallel-1: d5
parallel-1: ca
parallel-1: df
parallel-1: aa
parallel-1: d5
parallel-1: df
parallel-1: ff
parallel-1: c0
parallel-1: df
parallel-1: ff
parallel-1: ca
parallel-1: d7
parallel-1: ab
parallel-1: d5
parallel-1: ca
parallel-1: df
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: 7f
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff
parallel-1: ff

The trace above is for running:
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c W -a 0 TEST WRITE DATA
[+] Ready to write 15 bytes
[+] Write 15/15 (15 bytes)
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c R -a 0 -l 32
ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ%

**Comment by evgkarasev** [comment]
> You can try the version for other Arduino boards: https://github.com/Elrindel/Arduino-Flash-Programmer/blob/master/Arduino/Other/ArduinoFlashProgrammer/ArduinoFlashProgrammer.ino
> (This code is slower than the Uno/Nano version)

OK, will try

**Comment by evgkarasev** [comment]
Just re-flashed the Arduino, and now instead of FF it returns 7F :)
So in general nothing has been changed.

$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c I -x                  
7F 7F
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c W -a 0 TEST WRITE DATA
[+] Ready to write 15 bytes
[+] Write 15/15 (15 bytes)
$ python3 flashprogrammer.py -p /dev/ttyUSB0 -c R -a 0 -l 32 -x 
7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F 7F%

**Comment by evgkarasev** [comment]
Please could you check and reply the python configuration...

**Comment by Elrindel** [comment]
The writing sequence starts with these 3 bytes : AA 55 A0

This sequence is repeated for each byte to be written to the memory.

You either have a wiring problem or a problem with the configuration of your logic analyser (for parallel decoding, use WE as a clock signal with a falling edge).

**Comment by evgkarasev** [comment]
Thanks, checking the wiring once again...

https://www.futurlec.com/Datasheet/Memory/AT29C010.pdf

**Comment by evgkarasev** [comment]
Checked twice, no errors have been found...

The only thought that came in mind, that it could be linux serial driver /dev/ttyUSB0 that requires special care with processing in python... Will check on Windows machine

I have no other idea why it can't work as expected.

Any way, thanks a lot for your time and willingness to help!

**Comment by Elrindel** [comment]
I doubt that the problem is related to serial communication.

The sequence bytes (AA 55 A0 for writing) are not sent via serial communication, they are coded in the Arduino program (only the bytes to be written in the memory are sent via serial communication).
These bytes are sent on pins D2 to D9 (via registers PORTD and PORTB for the Uno/Nano code, and via digitalWrite for the other boards). You should see them with your logic analyser.

The message "[+] Ready to write %d bytes" is displayed only if the Arduino is ready to receive data, confirming that the serial communication is working properly.

So if you can't see the sequence bytes with your logic analyser then there is a problem, either in the Arduino or in your wiring.

You can try to remove the flash memory, start writing and see the result on your logic analyser (to make sure it is not your flash memory that is distorting the measurements).

If the measurements are correct without the flash memory, then it is possible that the OE or WE pin is faulty (or the memory chip is dead).

**Comment by evgkarasev** [comment]
Thank you for the explanation.

I have a bunch of AT29C010A flash chips bought on AliExpress, so already tried to change the chips - nothing changed.

Honestly speaking, this is my first expirience with Arduino, previously dealt with STM32 blue/black pills only. All the stuff was bought on AliExpress as well. I have tried only simple Blink example with Arduino so far. So next step will be 4-digit-7-segment-shift-register-counter on 74HC595.
https://create.arduino.cc/projecthub/goarray/4-digit-7-segment-shift-register-counter-b7338d

The reason why I spent such time on flashing the ROMs is the intention to build the Nibbler 4-bit 7400 CPU (https://www.bigmessowires.com/nibbler/) to teach my son CPU architecture.

All the details about that I would like to achieve are here:
https://github.com/pong74ls/Nibbler

**Comment by evgkarasev** [comment]
Good evening, Elrindel!

There are good and bad news...

The good one is that Arduino Nano board is fully functional! I have completed the 20x2 LCD output example and it works!
https://github.com/arduino-libraries/LiquidCrystal/tree/master/examples/HelloWorld

And the bad one - similar 20x2 LCD output example with 595 shift register doesn't work
https://github.com/matmunk/LiquidCrystal_74HC595

Thus it seems the problem is 595 shift register chips...
These chips are cheap so will change the whole bunch of them.

**Comment by Elrindel** [comment]
Hello,

You can easily test your 74HC595, here is an example: https://www.arduino.cc/en/Tutorial/Foundations/ShiftOut

Good luck!
