### ISSUE TITLE
Programmateur 27C010

### ISSUE THREAD

**Issue by ReasK29** [Elrindel/Arduino-Flash-Programmer#2]
Bonjour,

Tout d'abord, merci pour votre réponse.
En stage, je dois réaliser un programmateur pour AT27C010 pour faire de la lecture/écriture cette mémoire. Pour ma part, j'utilise un Raspberry Pi (avec Codeblocks en C). Le problème est que je ne peux pas attaquer directement la prom, le composant est monté sur une carte avec des composants pour serialiser les données.... J'ai routé une carte pour m'interfacer avec la carte existante. Il me reste la partie software à réaliser...
J'ai des séquences déjà décrite à coder en C en fonctions de mes entrées/sorties, j'ai validé ma lecture mais l'écriture me pose des soucis...
Mon sujet te parle t-il ? :)

**Comment by Elrindel** [comment]
Bonjour,

Votre mémoire AT27C010 n'est pas compatible avec mon programmateur via Arduino !

En effet, d'après le datasheet de l'AT27C010, l'écriture n'est pas gérée par une séquence mais via la broche VPP qui doit être à 13V.
Page 6 du datasheet : https://ww1.microchip.com/downloads/en/DeviceDoc/doc0321.pdf

On remarque également une augmentation de la tension VCC qui passe de 5V à 6.5V.

Ces tensions plus élevées semblent donc permettre de déclencher l'écriture lorsque la broche PGM passe à l'état bas. Il est ensuite très facile de vérifier que la donnée est bien écrite en repassant PGM à l'état haut puis OE à l'état bas afin de lire l'octet pour confirmer sont écriture.

Au niveau hardware c'est un peu plus contraignant à gérer car il faut pouvoir fournir les différentes tensions nécessaires, mais au niveau software c'est beaucoup plus rapide pour programmer la mémoire !

**Comment by ReasK29** [comment]
Je vois, d'accord...
Elrindel, auriez-vous un peu de temps pour regardez mon schéma ?
Cela m'aiderait beaucoup, je bloque vraiment sur la partie programmation

**Comment by Elrindel** [comment]
Il est préférable de vous rapprocher d'un forum d'électronique.
Personnellement je suis débutant en électronique.

Tout ce que je peux vous conseiller c'est de bien lire le datasheet du composant pour bien comprendre comment l'utiliser.
Ensuite, si le composant n'est pas directement accessible alors il faut trouver un moyen d'y accéder pour faire ce que vous souhaitez ... mais ce n'est pas forcément toujours possible sans intervenir directement sur le composant. Pour savoir cela il faut étudier/comprendre le schéma.

La programmation va juste consister à jouer avec l'état des GPIO pour envoyer/lire les bons signaux pour communiquer avec la mémoire.
En l'occurrence, si vous utilisez un RPi, les GPIO sont en 3.3V, donc dans tous les cas il faudra une solution hardware pour remonter les signaux au bon niveau pour gérer l'écriture (pour la lecture il est possible que 3.3V soit suffisant, mais je doute que ce soit le cas pour l'écriture).

Donc le plus gros du boulot est sur la partie hardware. De plus, le software va dépendre de vos choix pour la partie hardware ...

Encore une fois, le datasheet est le meilleur support ! Surtout que dans votre cas, le code sera vraiment simple comparé à mon code qui doit gérer des séquences.

**Comment by ReasK29** [comment]
J'ai déjà fait l'étude de la carte existante, et la partie hardware est finalisée. J'ai routé une carte sur laquelle sera pluggé le raspberry pi qui s'interface avec la carte existante. On ma donné un fichier excel avec les protocoles à coder : état haut, état bas des sorties. Il ne me reste que la partie software à valider (sans parler de l'intégration à la suite)
Mes fonctions à coder en C :
- Init à adresse 00
- Chargement adresse 13 bits
- Lecture d'une donnée
- écriture d'une donnée 

J'ai déjà consulter beaucoup de forum mais je n'avance pas dans mes fonctions en C... 
Je pourrai vous montrer le documents excel des fonctions que je dois coder ? 

Si ça ne vous dérange pas...

**Comment by Elrindel** [comment]
Si vous avez bien réalisé la partie hardware, il ne vous reste donc plus qu'à manipuler les GPIO du RPi.

Il y a énormément de tutos/exemples disponibles sur internet.
Voici les 2 premiers liens que j'ai trouvé et qui me semblent assez complets :
https://elinux.org/RPi_GPIO_Code_Samples
https://silanus.fr/bts/activites/raspberry/gpioRaspberryPi-SN2V1.html

Je n'ai jamais utilisé les GPIO d'un RPi mais de ce que je vois il existe plusieurs façons de procéder mais les différents exemples sont assez simples à comprendre.

Toutes les ressources dont vous avez besoin sont déjà disponibles sur internet et facilement trouvables avec une petite recherche.
L'apprentissage peut demander du temps mais c'est indispensable pour réaliser ce genre de projet soi-même.
