### ISSUE TITLE
Arduino code issue

### ISSUE THREAD

**Issue by Dale-Lien** [Elrindel/Arduino-Flash-Programmer#4]
Hi,
in ArduinoFlashProgrammer.ino,
line 190 (for UNO-Nano), line 232(for other):
	int32_t len = arg_to_int(serial_read_arg(), 1);

the parameter '1' mayby should be '-1'?
because the follower code are check
	if(address < 0 || len < 0){
		Serial.println("ERR");
		return;
	}

and the line 115 to 117 (for Other):
	digitalWrite(A0, (address>>16)&1);
	digitalWrite(A0, (address>>17)&1);
	digitalWrite(A0, (address>>18)&1);

should be:
	digitalWrite(A0, (address>>16)&1);
	digitalWrite(A1, (address>>17)&1);
	digitalWrite(A2, (address>>18)&1);

**Comment by Elrindel** [comment]
Hello,

The parameter is set to '1' on purpose.
This is the default value for reading. If no length is sent, it will read a single byte.

There was indeed a big mistake in the code of the set_address function in the assignment of the 3 most significant bits.
This is now fixed.

Thanks a lot!

**Comment by Dale-Lien** [comment]
Hi,
Thanks your answer.

I has make a clone on Mega2560, and it is work well.
